label Linux
    kernel /Image
    fdt /rk3566-acropi-lp4x.dtb
    append earlycon=uart8250,mmio32,0xfe660000 console=ttyS2,1500000n8 root=/dev/mmcblk0p4 ro rootfstype=squashfs rootwait nohz_full=2-3 rcu_nocbs=2-3 threadirqs isolcpus=2-3 idle=poll cpuidle.off=1
