# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-aarch64-rk3566-acropi"
BBFILE_PATTERN_meta-aarch64-rk3566-acropi = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-aarch64-rk3566-acropi = "6"

LAYERDEPENDS_meta-aarch64-rk3566-acropi = "core"
LAYERSERIES_COMPAT_meta-aarch64-rk3566-acropi = "walnascar"

DISTRO ??= "kpoky"