require conf/distro/poky.conf

DISTRO = "kpoky"
DISTRO_NAME = "KPOKY"
DISTRO_VERSION = "1.0"

PACKAGE_CLASSES = "package_ipk"
IMAGE_FEATURES += "package-management"
IMAGE_FEATURES += "ssh-server-dropbear"
IMAGE_INSTALL:append = " opkg"

# Ensure Machine extra deps are always included in images
IMAGE_INSTALL:append = " ${MACHINE_EXTRA_RDEPENDS}"
DISTRO_EXTRA_RDEPENDS += "i2c-tools v4l-utils networkmanager net-tools e2fsprogs-resize2fs parted android-tools openssh-sftp-server spidev-test gdb gdbserver htop tmux stress memtester rkaiq-3a-server rc-local nginx ruaps-cli extracustom-userapp sinffer devmem2 python3-pip python3-numpy python3-opencv libasan ttyd"
IMAGE_INSTALL:append = " ${DISTRO_EXTRA_RDEPENDS}"

INIT_MANAGER = "sysvinit"

# 继承自定义的 overlay class，处理最后阶段的 rootfs 文件覆盖
INHERIT += "kpoky-rootfs-overlay"

# Headless OpenCV configuration: Disable GTK, GStreamer, etc. to strip GUI dependencies
PACKAGECONFIG:pn-opencv = "python3 eigen jpeg png"

PACKAGECONFIG:append:pn-nginx = " webdav"



