require conf/distro/poky.conf

DISTRO = "kpoky"
DISTRO_NAME = "KPOKY"
DISTRO_VERSION = "1.0"

PACKAGE_CLASSES = "package_ipk"
IMAGE_FEATURES += "package-management"
IMAGE_FEATURES += "ssh-server-dropbear"
IMAGE_INSTALL:append = " opkg"

# Ensure Machine extra deps are always included in images
IMAGE_INSTALL:append = " ${MACHINE_EXTRA_RDEPENDS}"
DISTRO_EXTRA_RDEPENDS += "i2c-tools v4l-utils networkmanager net-tools e2fsprogs-resize2fs parted android-tools openssh-sftp-server spidev-test gdb gdbserver"
IMAGE_INSTALL:append = " ${DISTRO_EXTRA_RDEPENDS}"

INIT_MANAGER = "sysvinit"
