#!/bin/sh

case "$1" in
  start)
    echo "Setting up usb0 network..."
    sleep 2
    if [ -d /sys/class/net/usb0 ]; then
        ifconfig usb0 192.168.222.1 up
        udhcpd /etc/udhcpd.conf
    fi
    ;;
  stop)
    killall udhcpd
    ;;
esac
exit 0
